#!/bin/bash

# Set base name
base="bill-sharan-family"

# Starting counter
count=22

# Loop through jpg files
for file in *.JPG; do

  # Strip existing extension
  name=${file%.*}

  # Construct new name
  new="$base$count.jpg"

  # Rename file
  mv "$name.JPG" "$new"

  # Increment counter
  count=$((count+1))

done
