#!/bin/bash

# Set base name
base="nicholas-1-year-old-"

# Starting counter
count=1

# Loop through jpg files
for file in *.jpg; do

  # Strip existing extension
  name=${file%.*}

  # Construct new name
  new="$base$count.jpg"

  # Rename file
  mv "$name.jpg" "$new"

  # Increment counter
  count=$((count+1))

done

# Loop through JPG files
for file in *.JPG; do

  # Strip existing extension
  name=${file%.*}

  # Construct new name
  new="$base$count.jpg"

  # Rename file
  mv "$name.JPG" "$new"

  # Increment counter
  count=$((count+1))

done

mkdir thumbs
mogrify  -format gif -path thumbs -thumbnail 100x100 *.jpg

